name: Test workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          docker run -i --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME:$HOME" \
            -v "$PWD:$PWD" \
            -w "$PWD" \
            openjdk:11-slim \
            ./gradlew test
